[target.riscv32imac-unknown-none-elf]
runner = "espflash --release --monitor"

[build]
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core"]
